[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "LGPL-3.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
]

[bans]
multiple-versions = "deny"
skip = [
    # like everything
    { name = "cfg-if", version = "0.1.10" },
    # dev-deps
    { name = "itertools", version = "0.9" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"