[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "LGPL-3.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
]

[bans]
multiple-versions = "deny"
skip = [
    # parking_lot
    { name = "lock_api", version = "0.3.4" },
    # like everything
    { name = "cfg-if", version = "0.1.10" },
    # async-std
    { name = "crossbeam-utils", version = "0.7.2" }
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"